// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://regszcxpwikfctihfwqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZ3N6Y3hwd2lrZmN0aWhmd3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjAzMTYsImV4cCI6MjA3MDkzNjMxNn0.g_7of25dwDT4-Cdsc4GGZN9BoXVbM9XPb7lln5eT_8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});